# Generated by Django 5.2.17 on 2026-09-14 13:48

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Good",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "price_cents",
                    models.PositiveBigIntegerField(
                        help_text="Unit price in cents (100 = 1.00).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000000000),
                        ],
                    ),
                ),
                ("excluded_from_promotions", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="orders.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("price_cents", models.PositiveBigIntegerField()),
                ("discount", models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ("total_cents", models.PositiveBigIntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000),
                        ]
                    ),
                ),
                (
                    "price_cents",
                    models.PositiveBigIntegerField(help_text="Unit price snapshot in cents."),
                ),
                ("discount", models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ("total_cents", models.PositiveBigIntegerField()),
                (
                    "good",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="orders.good"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator("\\A[A-Za-z0-9_-]{1,64}\\Z")
                        ],
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Discount rate: 0.1 = 10%.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orders.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="promo_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="orders.promocode",
            ),
        ),
        migrations.AddConstraint(
            model_name="good",
            constraint=models.CheckConstraint(
                condition=models.Q(("price_cents__gte", 1), ("price_cents__lte", 1000000000)),
                name="good_price_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(fields=("order", "good"), name="order_good_once"),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1), ("quantity__lte", 10000)),
                name="item_quantity_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("price_cents__gte", 1), ("price_cents__lte", 1000000000)),
                name="item_price_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount__gte", 0), ("discount__lte", 1)),
                name="item_discount_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "total_cents__lte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("price_cents"), "*", models.F("quantity")
                        ),
                    )
                ),
                name="item_total_within_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="promocode",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount__gt", 0), ("discount__lte", 1)),
                name="promo_discount_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="promocode",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_uses__gte", 1)), name="promo_positive_limit"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                fields=("user", "promo_code"), name="order_user_promo_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_cents__lte", models.F("price_cents"))),
                name="order_total_within_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount__gte", 0), ("discount__lte", 1)),
                name="order_discount_range",
            ),
        ),
    ]
