# Generated by Django 5.2.17 on 2026-09-17 08:10

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import orders.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена одной единицы товара.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('10000000'))], verbose_name='цена')),
                ('excluded_from_promotions', models.BooleanField(default=False, verbose_name='исключён из акций')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создан')),
                ('price', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='стоимость до скидки')),
                ('discount', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='фактическая ставка скидки')),
                ('total', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='итого')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, verbose_name='ключ')),
                ('request_hash', models.CharField(editable=False, max_length=64, verbose_name='хеш запроса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('expires_at', models.DateTimeField(db_index=True, default=orders.models.idempotency_expiry, editable=False, verbose_name='истекает')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='idempotency_key', to='orders.order', verbose_name='заказ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'ключ идемпотентности',
                'verbose_name_plural': 'ключи идемпотентности',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, help_text='Снимок цены на момент создания заказа.', max_digits=10, verbose_name='цена за единицу')),
                ('discount', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='ставка скидки')),
                ('total', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='итого')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.good', verbose_name='товар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'строка заказа',
                'verbose_name_plural': 'строки заказа',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('\\A[A-Za-z0-9_-]{1,64}\\Z')], verbose_name='код')),
                ('discount', models.DecimalField(decimal_places=4, help_text='Доля от 0,0001 до 1: значение 0,1 означает скидку 10%.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0001')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='ставка скидки')),
                ('expires_at', models.DateTimeField(verbose_name='действует до')),
                ('max_uses', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='максимум использований')),
                ('uses_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='использовано')),
                ('category', models.ForeignKey(blank=True, help_text='Оставьте пустым, чтобы промокод действовал на все разрешённые товары.', null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.category', verbose_name='категория товаров')),
            ],
            options={
                'verbose_name': 'промокод',
                'verbose_name_plural': 'промокоды',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.promocode', verbose_name='промокод'),
        ),
        migrations.CreateModel(
            name='PromoCodeRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='погашен')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_redemption', to='orders.order', verbose_name='заказ')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.promocode', verbose_name='промокод')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'погашение промокода',
                'verbose_name_plural': 'погашения промокодов',
            },
        ),
        migrations.AddConstraint(
            model_name='good',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', Decimal('0.01')), ('price__lte', Decimal('10000000'))), name='good_price_range'),
        ),
        migrations.AddConstraint(
            model_name='orderidempotencykey',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='order_idempotency_user_key_once'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'good'), name='order_good_once'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 10000)), name='item_quantity_range'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', Decimal('0.01')), ('price__lte', Decimal('10000000'))), name='item_price_range'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', 0), ('discount__lte', 1)), name='item_discount_range'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0), ('total__lte', django.db.models.expressions.CombinedExpression(models.F('price'), '*', models.F('quantity')))), name='item_total_within_price'),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', Decimal('0.0001')), ('discount__lte', 1)), name='promo_discount_range'),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.CheckConstraint(condition=models.Q(('max_uses__gte', 1)), name='promo_positive_limit'),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.CheckConstraint(condition=models.Q(('uses_count__lte', models.F('max_uses'))), name='promo_usage_within_limit'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='order_positive_price'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0), ('total__lte', models.F('price'))), name='order_total_within_price'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', 0), ('discount__lte', 1)), name='order_discount_range'),
        ),
        migrations.AddConstraint(
            model_name='promocoderedemption',
            constraint=models.UniqueConstraint(fields=('user', 'promo_code'), name='promo_redemption_user_code_once'),
        ),
    ]
