# Generated by Django 5.2.17 on 2026-09-15 08:13

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_promo_redemptions(apps, schema_editor):
    order = apps.get_model("orders", "Order")
    redemption = apps.get_model("orders", "PromoCodeRedemption")
    database = schema_editor.connection.alias
    batch = []
    rows = (
        order.objects.using(database)
        .exclude(promo_code_id__isnull=True)
        .values_list("user_id", "promo_code_id", "pk", "created_at")
        .iterator(chunk_size=1000)
    )
    for user_id, promo_code_id, order_id, created_at in rows:
        batch.append(
            redemption(
                user_id=user_id,
                promo_code_id=promo_code_id,
                order_id=order_id,
                redeemed_at=created_at,
            )
        )
        if len(batch) == 1000:
            redemption.objects.using(database).bulk_create(batch)
            batch.clear()
    if batch:
        redemption.objects.using(database).bulk_create(batch)


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCodeRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "redeemed_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="promocode",
            name="promo_discount_range",
        ),
        migrations.AddConstraint(
            model_name="promocode",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount__gte", Decimal("0.0001")), ("discount__lte", 1)),
                name="promo_discount_range",
            ),
        ),
        migrations.AddField(
            model_name="promocoderedemption",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="promo_redemption",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="promocoderedemption",
            name="promo_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="orders.promocode"
            ),
        ),
        migrations.AddField(
            model_name="promocoderedemption",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="promocoderedemption",
            constraint=models.UniqueConstraint(
                fields=("user", "promo_code"), name="promo_redemption_user_code_once"
            ),
        ),
        migrations.RunPython(backfill_promo_redemptions, migrations.RunPython.noop),
    ]
