# Generated by Django 5.2.17 on 2026-09-15 20:10

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_promocoderedemption_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "категория", "verbose_name_plural": "категории"},
        ),
        migrations.AlterModelOptions(
            name="good",
            options={"verbose_name": "товар", "verbose_name_plural": "товары"},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "заказ", "verbose_name_plural": "заказы"},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"verbose_name": "строка заказа", "verbose_name_plural": "строки заказа"},
        ),
        migrations.AlterModelOptions(
            name="promocode",
            options={"verbose_name": "промокод", "verbose_name_plural": "промокоды"},
        ),
        migrations.AlterModelOptions(
            name="promocoderedemption",
            options={
                "verbose_name": "погашение промокода",
                "verbose_name_plural": "погашения промокодов",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=120, unique=True, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="good",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="orders.category",
                verbose_name="категория",
            ),
        ),
        migrations.AlterField(
            model_name="good",
            name="excluded_from_promotions",
            field=models.BooleanField(default=False, verbose_name="исключён из акций"),
        ),
        migrations.AlterField(
            model_name="good",
            name="name",
            field=models.CharField(max_length=200, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="good",
            name="price_cents",
            field=models.PositiveBigIntegerField(
                help_text="Цена одной единицы товара: 100 = 1,00 денежной единицы.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1000000000),
                ],
                verbose_name="цена в копейках",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="создан"),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=5, verbose_name="фактическая ставка скидки"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="price_cents",
            field=models.PositiveBigIntegerField(verbose_name="стоимость до скидки, в копейках"),
        ),
        migrations.AlterField(
            model_name="order",
            name="promo_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="orders.promocode",
                verbose_name="промокод",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_cents",
            field=models.PositiveBigIntegerField(verbose_name="итого, в копейках"),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="discount",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=5, verbose_name="ставка скидки"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="good",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="orders.good", verbose_name="товар"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.order",
                verbose_name="заказ",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price_cents",
            field=models.PositiveBigIntegerField(
                help_text="Снимок цены на момент создания заказа.",
                verbose_name="цена за единицу, в копейках",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10000),
                ],
                verbose_name="количество",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="total_cents",
            field=models.PositiveBigIntegerField(verbose_name="итого, в копейках"),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Оставьте пустым, чтобы промокод действовал на все разрешённые товары.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="orders.category",
                verbose_name="категория товаров",
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="code",
            field=models.CharField(
                max_length=64,
                unique=True,
                validators=[django.core.validators.RegexValidator("\\A[A-Za-z0-9_-]{1,64}\\Z")],
                verbose_name="код",
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="discount",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Доля от 0,0001 до 1: значение 0,1 означает скидку 10%.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0001")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
                verbose_name="ставка скидки",
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="expires_at",
            field=models.DateTimeField(verbose_name="действует до"),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="max_uses",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="максимум использований",
            ),
        ),
        migrations.AlterField(
            model_name="promocoderedemption",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="promo_redemption",
                to="orders.order",
                verbose_name="заказ",
            ),
        ),
        migrations.AlterField(
            model_name="promocoderedemption",
            name="promo_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="orders.promocode",
                verbose_name="промокод",
            ),
        ),
        migrations.AlterField(
            model_name="promocoderedemption",
            name="redeemed_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, verbose_name="погашен"
            ),
        ),
        migrations.AlterField(
            model_name="promocoderedemption",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
    ]
